### ISSUE TITLE
How to make an rarefaction curve based on single copy genes

### ISSUE THREAD

**Issue by SilasK** [metagenome-atlas/atlas#163]

**Comment by SilasK** [comment]
# 1. Cluster gene catalog with high sensitivity on nucleotide level
Change config file:
```
genecatalog:
  clustermethod: cd-hit-est 
  minlength_nt: 100
  minid: 0.98
  coverage: 0.9
  extra: ""
```

Run clustering and calculate abundance of genes:

`atlas assemble genecatalog`

(Atlas v2.1 `atlas run genecatalog` )

output can be found in **Genecatalog/counts**


#  2. Claissify single copy genes.

This is done with diamond, based on a databased shiped with DASTool, see it's article for more info.
There are defenetly better ways to do it, e.g. BUSCOs

 
`atlas assemble Genecatalog/annotation/single_copy_genes_bacteria.tsv`
`atlas assemble Genecatalog/annotation/single_copy_genes_archaea.tsv`
