### ISSUE TITLE
sbatch: error: invalid partition specified: bigmem

### ISSUE THREAD

**Issue by jjsanchezgil** [metagenome-atlas/atlas#364]
Hi, I have tried to run qc on a CentOS cluster system with slurm. I created the cluster profile and passed it to the command

> atlas run qc --profile cluster --working-dir /hpc/Metagenomes/ATLAS

However, I was getting this error during the calculate_insert_size step: `java.lang.OutOfMemoryError: Java heap space`, so I checked the cluster profile config file and I saw that all lines were commented. I removed the comments and added the calculate_insert_size to the queue `bigmem`. I am new to Snakemake and SLURM, so basically I simply tried what I thought was reasonable. This is right now my cluster_config.yaml:

```
## This is a yaml file, defining options for specific rules or by default.
## The '#' defines a comment.
## the two spaces at the beginning of rows below rulenames are important.
##Â For more information see https://snakemake.readthedocs.io/en/stable/executing/cluster-cloud.html#cluster-execution

# default parameter for all rules
__default__:
  queue: normal
  nodes: 1


# The following rules in atlas need need more time/memory.
# If you need to submit them to different queues you can configure this as outlined.

run_megahit:
  queue: bigmem
run_spades:
  queue: bigmem
calculate_insert_size:
  queue: bigmem

#gtdb-tk classify uses 'large_mem' and log time
classify:
  queue: bigmem-long

run_checkm_lineage_wf:
  queue: long

run_all_checkm_lineage_wf:
  queue: long

# You can  overwrite values for specific rules
# rulename:
#   queue: long
#   account: ""
#   time:  # h
#   threads:
```

I thought this would solve the heap space problem, but I got this error after re-running qc:

```
Exception: Job can't be submitted
sbatch: error: invalid partition specified: bigmem
sbatch: error: Batch job submission failed: Invalid partition name specified
```

I saw in key_mapping.yaml that queue values are passed to the `sbatch `command as partition names, and the output of `sinfo `doesn't show any partition with that name, but again I am new and I'm not sure of how it should actually work. How could I solve this?

Thanks a lot :)
