### ISSUE TITLE
Bins/MAGs with 0% completeness

### ISSUE THREAD

**Issue by MalbertR** [metagenome-atlas/atlas#378]
Hi,

I have had for a couple of different datasets MAGs with 0% completeness appearing in the genomic_bins_DASTool file, which is suppose to contain all the Bins/MAGs found in the dataset, right? 
How is it possible that there are MAGs of 0% completeness ending up in this file? And what does a completeness of 0% even mean? 

Thanks!

**Comment by SilasK** [comment]
First the genomic_bins_DASTool is not the final result, during the de-replication low-quality bins would be discarded. 

Completeness is the fraction of present/ expected marker genes. marker genes are genes that are found in 95% of all genomes within a group. This can be done at the domain level or at phylum or class level, with varying results. You can see the taxonomic level on which the quality estimation is based in the same file (something like Marker lineage),



If you are using the default config parameters, which are shown below, then my explanation would be that a bin is estimated by DAStool to be of 50% completeness but then measured by checkM it's completeness is of 0%. 

Such a bin could be a prokaryote genome with none of the marker genes present = crap, a virus, or a eukaryote. As said above it will be removed before the dereplication unless you changed the parameters not to filter. 

```
DASTool:
  search_engine: 'diamond'
  score_threshold: 0.5              #Score threshold until selection algorithm will keep selecting bins [0..1].

genome_dereplication:
  filter:
      noFilter: false
      length: 5000
      completeness: 50
      contamination: 10

```
